export const SEND_DRONE_REQUEST = 'SEND_DRONE_REQUEST'
export const SEND_DRONE_SUCCESS = 'SEND_DRONE_SUCCESST'
export const SEND_DRONE_ERROR = 'SEND_DRONE_ERROR'
export const DELETE_ERROR = 'DELETE_ERROR'